// Code generated by "stringer -type=ESize"; DO NOT EDIT.

package size

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[Bool-0]
	_ = x[Int32-1]
	_ = x[UInt32-2]
	_ = x[Float-3]
	_ = x[Int8-4]
	_ = x[UInt8-5]
	_ = x[Int16-6]
	_ = x[UInt16-7]
}

const _ESize_name = "BoolInt32Uint32FloatInt8Uint8Int16Uint16"

var _ESize_index = [...]uint8{0, 4, 9, 15, 20, 24, 29, 34, 40}

func (i ESize) String() string {
	if i >= ESize(len(_ESize_index)-1) {
		return "ESize(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _ESize_name[_ESize_index[i]:_ESize_index[i+1]]
}
