// Code generated by "stringer -type=EGroupBit"; DO NOT EDIT.

package groupbit

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[Vars-1]
	_ = x[CVars-2]
	_ = x[GVars-4]
	_ = x[SVars-8]
	_ = x[All-15]
}

const (
	_EGroupBit_name_0 = "VarsCVars"
	_EGroupBit_name_1 = "GVars"
	_EGroupBit_name_2 = "SVars"
	_EGroupBit_name_3 = "All"
)

var (
	_EGroupBit_index_0 = [...]uint8{0, 4, 9}
)

func (i EGroupBit) String() string {
	switch {
	case 1 <= i && i <= 2:
		i -= 1
		return _EGroupBit_name_0[_EGroupBit_index_0[i]:_EGroupBit_index_0[i+1]]
	case i == 4:
		return _EGroupBit_name_1
	case i == 8:
		return _EGroupBit_name_2
	case i == 15:
		return _EGroupBit_name_3
	default:
		return "EGroupBit(" + strconv.FormatInt(int64(i), 10) + ")"
	}
}
