// Code generated by "stringer -type=ESaveVarCategory"; DO NOT EDIT.

package savevarcategory

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[None-0]
	_ = x[Config-1]
	_ = x[MissionRestartable-2]
	_ = x[GameGlobal-4]
	_ = x[Mission-8]
	_ = x[Retry-16]
	_ = x[MbManagement-32]
	_ = x[Quest-64]
	_ = x[Personal-128]
}

const (
	_ESaveVarCategory_name_0 = "NoneConfigMissionRestartable"
	_ESaveVarCategory_name_1 = "GameGlobal"
	_ESaveVarCategory_name_2 = "Mission"
	_ESaveVarCategory_name_3 = "Retry"
	_ESaveVarCategory_name_4 = "MbManagement"
	_ESaveVarCategory_name_5 = "Quest"
	_ESaveVarCategory_name_6 = "Personal"
)

var (
	_ESaveVarCategory_index_0 = [...]uint8{0, 4, 10, 28}
)

func (i ESaveVarCategory) String() string {
	switch {
	case i <= 2:
		return _ESaveVarCategory_name_0[_ESaveVarCategory_index_0[i]:_ESaveVarCategory_index_0[i+1]]
	case i == 4:
		return _ESaveVarCategory_name_1
	case i == 8:
		return _ESaveVarCategory_name_2
	case i == 16:
		return _ESaveVarCategory_name_3
	case i == 32:
		return _ESaveVarCategory_name_4
	case i == 64:
		return _ESaveVarCategory_name_5
	case i == 128:
		return _ESaveVarCategory_name_6
	default:
		return "ESaveVarCategory(" + strconv.FormatInt(int64(i), 10) + ")"
	}
}
