// Code generated by "stringer -type=ESaveType"; DO NOT EDIT.

package savetype

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[GAME-0]
	_ = x[CONFIG-1]
	_ = x[PERSONAL-2]
	_ = x[GRAPHICS-3]
	_ = x[MGO-4]
}

const _ESaveType_name = "GAMECONFIGPERSONALGRAPHICSMGO"

var _ESaveType_index = [...]uint8{0, 4, 10, 18, 26, 29}

func (i ESaveType) String() string {
	if i >= ESaveType(len(_ESaveType_index)-1) {
		return "ESaveType(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _ESaveType_name[_ESaveType_index[i]:_ESaveType_index[i+1]]
}
